services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
    networks:
      - node-red-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=${MAILGUN_HOST}
      - GF_SMTP_USER=${MAILGUN_EMAIL}
      - GF_SMTP_PASSWORD=${MAILGUN_PASSWORD}
      - GF_SMTP_SKIP_VERIFY=false
      - GF_SMTP_FROM_NAME=grafana
      - GF_SMTP_FROM_ADDRESS=${MAILGUN_EMAIL}
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/data:/var/lib/grafana
    networks:
      - node-red-net

  node-red:
    stdin_open: true
    tty: true
    ports:
      - 1880:1880
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - FLOWS=flows.json
    volumes:
      - ./node-red-data:/data
    container_name: mynodered
    image: nodered/node-red
    networks:
      - node-red-net

  node-exporter:
    image: prom/node-exporter:latest
    volumes:
      - ./node-exporter:/textfile_collector
    command:
      - '--collector.textfile.directory=/textfile_collector'
    ports:
      - "9100:9100"
    networks:
      - node-red-net

volumes:
  prom_data:
  node-red-data:

networks:
  node-red-net:
