services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus-ship-track
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 4444:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data_ship_track:/prometheus
    networks:
      - ship-track-net
  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway-ship-track
    ports:
      - 4447:9091
    restart: unless-stopped
    networks:
      - ship-track-net

  grafana:
    image: benneuville/grafana-track-ship
    platform: linux/amd64
    container_name: grafana-ship-track
    ports:
      - 4445:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=${MAILGUN_HOST}
      - GF_SMTP_USER=${MAILGUN_EMAIL}
      - GF_SMTP_PASSWORD=${MAILGUN_PASSWORD}
      - GF_SMTP_SKIP_VERIFY=false
      - GF_SMTP_FROM_NAME=grafana
      - GF_SMTP_FROM_ADDRESS=${MAILGUN_EMAIL}
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/data:/var/lib/grafana
    user: "472:472"
    networks:
      - ship-track-net
  nginx:
    image: nginx:latest
    container_name: nginx-data-ship-track
    ports:
      - "3030:80"
    restart: unless-stopped
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./datas:/usr/share/nginx/html/datas
    networks:
      - ship-track-net
  consumer:
    build: ./mqtt-consumer
    container_name: consumer-ship-track
    volumes:
      - ./mqtt-consumer:/app
    command: python consumer.py
    networks:
      - ship-track-net
    depends_on:
      - pushgateway
      - prometheus
      - grafana
      - nginx

volumes:
  prom_data_ship_track:

networks:
  ship-track-net:
    driver: bridge
